name: Add Pull Request Checklist

on:
  pull_request:
    types:
      - opened

jobs:
  add_checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add checklist to pull request
      run: |
        checklist="## チェックリスト\n- [ ] API側の修正がある\n  - [ ] マイグレーションが必要\n- [ ] リロードが必須\n- [ ] 外部サービスのデプロイや修正がある\n- [ ] 環境変数の設定が必要"
        echo "$checklist" >> $GITHUB_WORKSPACE/$GITHUB_REPOSITORY_PATH
      env:
        GITHUB_REPOSITORY_PATH: ${{ github.event.pull_request.base.repo.full_name }}