name: Add Pull Request Checklist

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  add_checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Checklist Comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        checklist="**メンテナンス必須チェックシート**\n\n- [ ] API側の修正がある\n  - [ ] マイグレーションが必要\n- [ ] リロードが必須\n- [ ] 外部サービスのデプロイや修正がある\n- [ ] 環境変数の設定が必要"
        comment_url=$(curl -X POST -s -H "Authorization: Bearer $GITHUB_TOKEN" -d "{\"body\":\"$checklist\"}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${{ github.event.pull_request.number }}/comments" | jq -r .url)
        echo "::set-output name=comment_url::$comment_url"