name: Add Pull Request Checklist

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  add_checklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Checklist Comment
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const body ="##メンテナンス必須チェックシート\n\n- [ ] API側の修正がある\n  - [ ] マイグレーションが必要\n- [ ] リロードが必須\n- [ ] 外部サービスのデプロイや修正がある\n- [ ] 環境変数の設定が必要"
          const params = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: '${{ steps.opening_announce.outputs.message }}'
          }
          await github.rest.issues.createComment(params)